services:
  db:
    image: postgres
    volumes:
      - flask_postgresql_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  flask:
    build:
      context: .
    ports:
    # Host:Container
      - "8080:5000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - "./flask_web_app:/app"
volumes:
  flask_postgresql_vol:
    external: true
# docker compose up && docker exec -it <container_name> /bin/bash
