"""Initial migration.

Revision ID: 822a6e3bd253
Revises: 
Create Date: 2023-03-26 08:54:23.342436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822a6e3bd253'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
